name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          file: Dockerfile
          push: true
          tags: ghcr.io/ebtsi/caddy-porkbun-docker
